### ISSUE TITLE
Ceiling SR mesh isn't shown - the lander behaves unexpectedly

### ISSUE THREAD

**Issue by radicalad** [Microsoft/MRDesignLabs_Unity_LunarModule#1]
At the moment we don't put a texture on the mesh so the lander blows up without notice. I'd recommend removing the ceiling SR mesh to give the lander more wiggle room.

**Comment by taylorjames9** [comment]
This is related to the lander exploding unexpectedly on the ceiling. Two things have been done to resolve this issue: 1.) The ceiling SR is no longer shown. (The shader now fades out the SR mesh walls when they get close to the ceiling. 2.) The lander no longer detects collisions above the eye height of the user. As long as the user is shorter than the ceiling, then lander will not collide with the SR ceiling mesh.
